Traceback (most recent call last):
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pcm.Plot_Map(np.fft.ifft(Sout[:,:,1],axis=1),np.arange(dOm.size),xlabel='Detuning index', units='')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/sn/qf84cb8n2jn9khwk0csmq2l80000gq/T/ipykernel_50064/22020661.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mpcm[0m[0;34m.[0m[0mPlot_Map[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0mfft[0m[0;34m.[0m[0mifft[0m[0;34m([0m[0mSout[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m[0;34m:[0m[0;34m,[0m[0;36m1[0m[0;34m][0m[0;34m,[0m[0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m,[0m[0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0mdOm[0m[0;34m.[0m[0msize[0m[0;34m)[0m[0;34m,[0m[0mxlabel[0m[0;34m=[0m[0;34m'Detuning index'[0m[0;34m,[0m [0munits[0m[0;34m=[0m[0;34m''[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'Sout' is not defined
NameError: name 'Sout' is not defined

